INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302672,'AD','Andorra','EU','https://en.wikipedia.org/wiki/Andorra',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302618,'AE','United Arab Emirates','AS','https://en.wikipedia.org/wiki/United_Arab_Emirates','UAE,Ù…Ø·Ø§Ø±Ø§Øª ÙÙŠ Ø§Ù„Ø¥Ù…Ø§Ø±Ø§Øª Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© Ø§Ù„Ù…ØªØ­Ø¯Ø©');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302619,'AF','Afghanistan','AS','https://en.wikipedia.org/wiki/Afghanistan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302722,'AG','Antigua and Barbuda','NA','https://en.wikipedia.org/wiki/Antigua_and_Barbuda',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302723,'AI','Anguilla','NA','https://en.wikipedia.org/wiki/Anguilla',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302673,'AL','Albania','EU','https://en.wikipedia.org/wiki/Albania',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302620,'AM','Armenia','AS','https://en.wikipedia.org/wiki/Armenia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302556,'AO','Angola','AF','https://en.wikipedia.org/wiki/Angola',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302615,'AQ','Antarctica','AN','https://en.wikipedia.org/wiki/Antarctica',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302789,'AR','Argentina','SA','https://en.wikipedia.org/wiki/Argentina','Aeropuertos de Argentina');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302763,'AS','American Samoa','OC','https://en.wikipedia.org/wiki/American_Samoa',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302674,'AT','Austria','EU','https://en.wikipedia.org/wiki/Austria','FlughÃ¤fen in Ã–sterreich');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302764,'AU','Australia','OC','https://en.wikipedia.org/wiki/Australia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302725,'AW','Aruba','NA','https://en.wikipedia.org/wiki/Aruba',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302621,'AZ','Azerbaijan','AS','https://en.wikipedia.org/wiki/Azerbaijan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302675,'BA','Bosnia and Herzegovina','EU','https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302726,'BB','Barbados','NA','https://en.wikipedia.org/wiki/Barbados',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302622,'BD','Bangladesh','AS','https://en.wikipedia.org/wiki/Bangladesh',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302676,'BE','Belgium','EU','https://en.wikipedia.org/wiki/Belgium','AÃ©roports de Belgique,Luchthavens van BelgiÃ«');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302557,'BF','Burkina Faso','AF','https://en.wikipedia.org/wiki/Burkina_Faso',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302677,'BG','Bulgaria','EU','https://en.wikipedia.org/wiki/Bulgaria',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302623,'BH','Bahrain','AS','https://en.wikipedia.org/wiki/Bahrain','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ø¨Ø­Ø±ÙŠÙ†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302558,'BI','Burundi','AF','https://en.wikipedia.org/wiki/Burundi',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302559,'BJ','Benin','AF','https://en.wikipedia.org/wiki/Benin',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302760,'BL','Saint BarthÃ©lemy','NA','https://en.wikipedia.org/wiki/Saint_BarthÃ©lemy',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302727,'BM','Bermuda','NA','https://en.wikipedia.org/wiki/Bermuda',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302624,'BN','Brunei','AS','https://en.wikipedia.org/wiki/Brunei',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302790,'BO','Bolivia','SA','https://en.wikipedia.org/wiki/Bolivia','Aeropuertos de Bolivia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302724,'BQ','Caribbean Netherlands','NA','https://en.wikipedia.org/wiki/Caribbean_Netherlands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302791,'BR','Brazil','SA','https://en.wikipedia.org/wiki/Brazil','Brasil, Brasilian');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302728,'BS','Bahamas','NA','https://en.wikipedia.org/wiki/Bahamas',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302625,'BT','Bhutan','AS','https://en.wikipedia.org/wiki/Bhutan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302560,'BW','Botswana','AF','https://en.wikipedia.org/wiki/Botswana',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302678,'BY','Belarus','EU','https://en.wikipedia.org/wiki/Belarus','Belarussian, Ð‘ÐµÐ»Ð°Ñ€ÑƒÑÑŒ');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302729,'BZ','Belize','NA','https://en.wikipedia.org/wiki/Belize',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302730,'CA','Canada','NA','https://en.wikipedia.org/wiki/Canada',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302626,'CC','Cocos (Keeling) Islands','AS','https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302561,'CD','Congo (Kinshasa)','AF','https://en.wikipedia.org/wiki/Congo_(Kinshasa)',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302562,'CF','Central African Republic','AF','https://en.wikipedia.org/wiki/Central_African_Republic',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302563,'CG','Congo (Brazzaville)','AF','https://en.wikipedia.org/wiki/Congo_(Brazzaville)',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302679,'CH','Switzerland','EU','https://en.wikipedia.org/wiki/Switzerland','AÃ©roports de la Suisse,FlughÃ¤fen der Schweiz');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302564,'CI','CÃ´te d''Ivoire','AF','https://en.wikipedia.org/wiki/CÃ´te_d''Ivoire','Ivory Coast');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302765,'CK','Cook Islands','OC','https://en.wikipedia.org/wiki/Cook_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302792,'CL','Chile','SA','https://en.wikipedia.org/wiki/Chile','Aeropuertos de Chile');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302565,'CM','Cameroon','AF','https://en.wikipedia.org/wiki/Cameroon',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302627,'CN','China','AS','https://en.wikipedia.org/wiki/China','ä¸­å›½çš„æœºåœº');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302793,'CO','Colombia','SA','https://en.wikipedia.org/wiki/Colombia','Aeropuertos de Colombia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302731,'CR','Costa Rica','NA','https://en.wikipedia.org/wiki/Costa_Rica','Aeropuertos de Costa Rica');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302732,'CU','Cuba','NA','https://en.wikipedia.org/wiki/Cuba','Aeropuertos de Cuba');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302566,'CV','Cape Verde','AF','https://en.wikipedia.org/wiki/Cape_Verde',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302762,'CW','CuraÃ§ao','NA','https://en.wikipedia.org/wiki/Cura%C3%A7ao',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302628,'CX','Christmas Island','AS','https://en.wikipedia.org/wiki/Christmas_Island',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302629,'CY','Cyprus','AS','https://en.wikipedia.org/wiki/Cyprus',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302680,'CZ','Czech Republic','EU','https://en.wikipedia.org/wiki/Czech_Republic','LetiÅ¡tÄ› ÄŒeskÃ© republiky, Czechia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302681,'DE','Germany','EU','https://en.wikipedia.org/wiki/Germany','FlughÃ¤fen in Deutschland');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302567,'DJ','Djibouti','AF','https://en.wikipedia.org/wiki/Djibouti',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302682,'DK','Denmark','EU','https://en.wikipedia.org/wiki/Denmark','Lufthavnene i Danmark');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302733,'DM','Dominica','NA','https://en.wikipedia.org/wiki/Dominica',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302734,'DO','Dominican Republic','NA','https://en.wikipedia.org/wiki/Dominican_Republic',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302568,'DZ','Algeria','AF','https://en.wikipedia.org/wiki/Algeria','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ø¬Ø²Ø§Ø¦Ø±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302794,'EC','Ecuador','SA','https://en.wikipedia.org/wiki/Ecuador','Aeropuertos de Ecuador');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302683,'EE','Estonia','EU','https://en.wikipedia.org/wiki/Estonia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302569,'EG','Egypt','AF','https://en.wikipedia.org/wiki/Egypt','Ù…Ø·Ø§Ø±Ø§Øª Ù…ØµØ±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302570,'EH','Western Sahara','AF','https://en.wikipedia.org/wiki/Western_Sahara','Sahrawian, Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„ØµØ­Ø±Ø§Ø¡ Ø§Ù„ØºØ±Ø¨ÙŠØ©');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302571,'ER','Eritrea','AF','https://en.wikipedia.org/wiki/Eritrea',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302684,'ES','Spain','EU','https://en.wikipedia.org/wiki/Spain','Aeropuertos de EspaÃ±a');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302572,'ET','Ethiopia','AF','https://en.wikipedia.org/wiki/Ethiopia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302685,'FI','Finland','EU','https://en.wikipedia.org/wiki/Finland','LentokentÃ¤t, Suomen');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302766,'FJ','Fiji','OC','https://en.wikipedia.org/wiki/Fiji',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302795,'FK','Falkland Islands','SA','https://en.wikipedia.org/wiki/Falkland_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302767,'FM','Micronesia','OC','https://en.wikipedia.org/wiki/Federated_States_of_Micronesia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302686,'FO','Faroe Islands','EU','https://en.wikipedia.org/wiki/Faroe_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302687,'FR','France','EU','https://en.wikipedia.org/wiki/France','AÃ©roports de France');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302573,'GA','Gabon','AF','https://en.wikipedia.org/wiki/Gabon',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302688,'GB','United Kingdom','EU','https://en.wikipedia.org/wiki/United_Kingdom','Great Britain');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302735,'GD','Grenada','NA','https://en.wikipedia.org/wiki/Grenada',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302630,'GE','Georgia','AS','https://en.wikipedia.org/wiki/Georgia_(country)',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302796,'GF','French Guiana','SA','https://en.wikipedia.org/wiki/French_Guiana','French Guyana');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302689,'GG','Guernsey','EU','https://en.wikipedia.org/wiki/Guernsey',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302574,'GH','Ghana','AF','https://en.wikipedia.org/wiki/Ghana',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302690,'GI','Gibraltar','EU','https://en.wikipedia.org/wiki/Gibraltar',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302736,'GL','Greenland','NA','https://en.wikipedia.org/wiki/Greenland',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302575,'GM','Gambia','AF','https://en.wikipedia.org/wiki/Gambia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302576,'GN','Guinea','AF','https://en.wikipedia.org/wiki/Guinea','AÃ©roports de la GuinÃ©e');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302737,'GP','Guadeloupe','NA','https://en.wikipedia.org/wiki/Guadeloupe',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302577,'GQ','Equatorial Guinea','AF','https://en.wikipedia.org/wiki/Equatorial_Guinea',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302691,'GR','Greece','EU','https://en.wikipedia.org/wiki/Greece','Î±ÎµÏÎ¿Î´ÏÏŒÎ¼Î¹Î± ÏƒÏ„Î·Î½ Î•Î»Î»Î¬Î´Î±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302616,'GS','South Georgia and the South Sandwich Islands','AN','https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302738,'GT','Guatemala','NA','https://en.wikipedia.org/wiki/Guatemala','Aeropuertos de Guatemala');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302768,'GU','Guam','OC','https://en.wikipedia.org/wiki/Guam',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302578,'GW','Guinea-Bissau','AF','https://en.wikipedia.org/wiki/Guinea-Bissau',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302797,'GY','Guyana','SA','https://en.wikipedia.org/wiki/Guyana',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302631,'HK','Hong Kong','AS','https://en.wikipedia.org/wiki/Hong_Kong',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302739,'HN','Honduras','NA','https://en.wikipedia.org/wiki/Honduras','Aeropuertos de Honduras');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302692,'HR','Croatia','EU','https://en.wikipedia.org/wiki/Croatia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302740,'HT','Haiti','NA','https://en.wikipedia.org/wiki/Haiti','AÃ©roports de HaÃ¯ti');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302693,'HU','Hungary','EU','https://en.wikipedia.org/wiki/Hungary','RepÃ¼lÅ‘terek MagyarorszÃ¡g');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302632,'ID','Indonesia','AS','https://en.wikipedia.org/wiki/Indonesia','Bandara di Indonesia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302694,'IE','Ireland','EU','https://en.wikipedia.org/wiki/Ireland','Eire');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302633,'IL','Israel','AS','https://en.wikipedia.org/wiki/Israel','×©×“×•×ª ×”×ª×¢×•×¤×” ×©×œ ×™×©×¨××œ');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302695,'IM','Isle of Man','EU','https://en.wikipedia.org/wiki/Isle_of_Man',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302634,'IN','India','AS','https://en.wikipedia.org/wiki/India',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302635,'IO','British Indian Ocean Territory','AS','https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302636,'IQ','Iraq','AS','https://en.wikipedia.org/wiki/Iraq','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ø¹Ø±Ø§Ù‚');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302637,'IR','Iran','AS','https://en.wikipedia.org/wiki/Iran','ÙØ±ÙˆØ¯Ú¯Ø§Ù‡ Ù‡Ø§ÛŒ Ø§ÛŒØ±Ø§Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302696,'IS','Iceland','EU','https://en.wikipedia.org/wiki/Iceland',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302697,'IT','Italy','EU','https://en.wikipedia.org/wiki/Italy','Aeroporti d''Italia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302698,'JE','Jersey','EU','https://en.wikipedia.org/wiki/Jersey',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302741,'JM','Jamaica','NA','https://en.wikipedia.org/wiki/Jamaica',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302638,'JO','Jordan','AS','https://en.wikipedia.org/wiki/Jordan','Ù…Ø·Ø§Ø±Ø§Øª ÙÙŠ Ø§Ù„Ø£Ø±Ø¯Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302639,'JP','Japan','AS','https://en.wikipedia.org/wiki/Japan','Nippon, æ—¥æœ¬ã®ç©ºæ¸¯');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302579,'KE','Kenya','AF','https://en.wikipedia.org/wiki/Kenya',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302640,'KG','Kyrgyzstan','AS','https://en.wikipedia.org/wiki/Kyrgyzstan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302641,'KH','Cambodia','AS','https://en.wikipedia.org/wiki/Cambodia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302769,'KI','Kiribati','OC','https://en.wikipedia.org/wiki/Kiribati',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302580,'KM','Comoros','AF','https://en.wikipedia.org/wiki/Comoros','Ø¬Ø²Ø± Ø§Ù„Ù‚Ù…Ø±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302742,'KN','Saint Kitts and Nevis','NA','https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302642,'KP','North Korea','AS','https://en.wikipedia.org/wiki/North_Korea',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302643,'KR','South Korea','AS','https://en.wikipedia.org/wiki/South_Korea','í•œêµ­ì˜ ê³µí•­');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302644,'KW','Kuwait','AS','https://en.wikipedia.org/wiki/Kuwait',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302743,'KY','Cayman Islands','NA','https://en.wikipedia.org/wiki/Cayman_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302645,'KZ','Kazakhstan','AS','https://en.wikipedia.org/wiki/Kazakhstan','Kazakh');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302646,'LA','Laos','AS','https://en.wikipedia.org/wiki/Laos',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302647,'LB','Lebanon','AS','https://en.wikipedia.org/wiki/Lebanon','Ø§Ù„Ù…Ø·Ø§Ø±Ø§Øª ÙÙŠ Ù„Ø¨Ù†Ø§Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302744,'LC','Saint Lucia','NA','https://en.wikipedia.org/wiki/Saint_Lucia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302699,'LI','Liechtenstein','EU','https://en.wikipedia.org/wiki/Liechtenstein',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302648,'LK','Sri Lanka','AS','https://en.wikipedia.org/wiki/Sri_Lanka',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302581,'LR','Liberia','AF','https://en.wikipedia.org/wiki/Liberia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302582,'LS','Lesotho','AF','https://en.wikipedia.org/wiki/Lesotho',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302700,'LT','Lithuania','EU','https://en.wikipedia.org/wiki/Lithuania',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302701,'LU','Luxembourg','EU','https://en.wikipedia.org/wiki/Luxembourg',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302702,'LV','Latvia','EU','https://en.wikipedia.org/wiki/Latvia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302583,'LY','Libya','AF','https://en.wikipedia.org/wiki/Libya','Ù…Ø·Ø§Ø±Ø§Øª ÙÙŠ Ù„ÙŠØ¨ÙŠØ§');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302584,'MA','Morocco','AF','https://en.wikipedia.org/wiki/Morocco','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ù…ØºØ±Ø¨');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302703,'MC','Monaco','EU','https://en.wikipedia.org/wiki/Monaco',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302704,'MD','Moldova','EU','https://en.wikipedia.org/wiki/Moldova',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302705,'ME','Montenegro','EU','https://en.wikipedia.org/wiki/Montenegro',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302759,'MF','Saint Martin','NA','https://en.wikipedia.org/wiki/Saint_Martin_(France)',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302585,'MG','Madagascar','AF','https://en.wikipedia.org/wiki/Madagascar',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302770,'MH','Marshall Islands','OC','https://en.wikipedia.org/wiki/Marshall_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302706,'MK','North Macedonia','EU','https://en.wikipedia.org/wiki/Macedonia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302586,'ML','Mali','AF','https://en.wikipedia.org/wiki/Mali','AÃ©roports du Mali');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302649,'MM','Burma','AS','https://en.wikipedia.org/wiki/Burma','Myanmar');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302650,'MN','Mongolia','AS','https://en.wikipedia.org/wiki/Mongolia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302651,'MO','Macau','AS','https://en.wikipedia.org/wiki/Macau','Macao');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302771,'MP','Northern Mariana Islands','OC','https://en.wikipedia.org/wiki/Northern_Mariana_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302745,'MQ','Martinique','NA','https://en.wikipedia.org/wiki/Martinique',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302587,'MR','Mauritania','AF','https://en.wikipedia.org/wiki/Mauritania','Ù…Ø·Ø§Ø±Ø§Øª Ù…ÙˆØ±ÙŠØªØ§Ù†ÙŠØ§');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302746,'MS','Montserrat','NA','https://en.wikipedia.org/wiki/Montserrat',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302707,'MT','Malta','EU','https://en.wikipedia.org/wiki/Malta',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302588,'MU','Mauritius','AF','https://en.wikipedia.org/wiki/Mauritius',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302652,'MV','Maldives','AS','https://en.wikipedia.org/wiki/Maldives',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302589,'MW','Malawi','AF','https://en.wikipedia.org/wiki/Malawi',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302747,'MX','Mexico','NA','https://en.wikipedia.org/wiki/Mexico','Aeropuertos de MÃ©xico');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302653,'MY','Malaysia','AS','https://en.wikipedia.org/wiki/Malaysia','Lapangan Terbang Malaysia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302590,'MZ','Mozambique','AF','https://en.wikipedia.org/wiki/Mozambique',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302591,'NA','Namibia','AF','https://en.wikipedia.org/wiki/Namibia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302772,'NC','New Caledonia','OC','https://en.wikipedia.org/wiki/New_Caledonia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302592,'NE','Niger','AF','https://en.wikipedia.org/wiki/Niger',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302773,'NF','Norfolk Island','OC','https://en.wikipedia.org/wiki/Norfolk_Island',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302593,'NG','Nigeria','AF','https://en.wikipedia.org/wiki/Nigeria',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302748,'NI','Nicaragua','NA','https://en.wikipedia.org/wiki/Nicaragua','Aeropuertos de Nicaragua');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302708,'NL','Netherlands','EU','https://en.wikipedia.org/wiki/Netherlands','Holland,Luchthavens van Nederland');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302709,'NO','Norway','EU','https://en.wikipedia.org/wiki/Norway','Flyplasser i Norge');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302654,'NP','Nepal','AS','https://en.wikipedia.org/wiki/Nepal','à¤¨à¥‡à¤ªà¤¾à¤² à¤µà¤¿à¤®à¤¾à¤¨à¤¸à¥à¤¥à¤²à¤•à¥‹');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302774,'NR','Nauru','OC','https://en.wikipedia.org/wiki/Nauru',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302775,'NU','Niue','OC','https://en.wikipedia.org/wiki/Niue',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302776,'NZ','New Zealand','OC','https://en.wikipedia.org/wiki/New_Zealand',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302655,'OM','Oman','AS','https://en.wikipedia.org/wiki/Oman','Ù…Ø·Ø§Ø±Ø§Øª Ø¹Ù…Ø§Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302749,'PA','Panama','NA','https://en.wikipedia.org/wiki/Panama','Aeropuertos de PanamÃ¡');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302798,'PE','PerÃº','SA','https://en.wikipedia.org/wiki/PerÃº','Aeropuertos de PerÃº');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302777,'PF','French Polynesia','OC','https://en.wikipedia.org/wiki/French_Polynesia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302778,'PG','Papua New Guinea','OC','https://en.wikipedia.org/wiki/Papua_New_Guinea',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302656,'PH','Philippines','AS','https://en.wikipedia.org/wiki/Philippines','Mga alternatibong byahe mula sa Pilipinas');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302657,'PK','Pakistan','AS','https://en.wikipedia.org/wiki/Pakistan','Ù¾Ø§Ú©Ø³ØªØ§Ù† Ú©Û’ ÛÙˆØ§Ø¦ÛŒ Ø§ÚˆÙˆÚº');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302710,'PL','Poland','EU','https://en.wikipedia.org/wiki/Poland','Lotniska Polski');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302750,'PM','Saint Pierre and Miquelon','NA','https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302779,'PN','Pitcairn','OC','https://en.wikipedia.org/wiki/Pitcairn',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302751,'PR','Puerto Rico','NA','https://en.wikipedia.org/wiki/Puerto_Rico',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302658,'PS','Palestinian Territory','AS','https://en.wikipedia.org/wiki/Palestinian_Territory',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302711,'PT','Portugal','EU','https://en.wikipedia.org/wiki/Portugal','Aeroportos do Brasil');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302780,'PW','Palau','OC','https://en.wikipedia.org/wiki/Palau',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302799,'PY','Paraguay','SA','https://en.wikipedia.org/wiki/Paraguay','Aeropuertos de Paraguay');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302659,'QA','Qatar','AS','https://en.wikipedia.org/wiki/Qatar','Ù…Ø·Ø§Ø±Ø§Øª Ù‚Ø·Ø±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302594,'RE','RÃ©union','AF','https://en.wikipedia.org/wiki/RÃ©union','ÃŽle Bourbon, La RÃ©union');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302712,'RO','Romania','EU','https://en.wikipedia.org/wiki/Romania','Aeroporturi din RomÃ¢nia');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302713,'RS','Serbia','EU','https://en.wikipedia.org/wiki/Serbia','Serb');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302714,'RU','Russia','EU','https://en.wikipedia.org/wiki/Russia','Soviet, Sovietskaya, Sovetskaya, ÐÑÑ€Ð¾Ð¿Ð¾Ñ€Ñ‚Ñ‹ Ð Ð¾ÑÑÐ¸Ð¸');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302595,'RW','Rwanda','AF','https://en.wikipedia.org/wiki/Rwanda',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302660,'SA','Saudi Arabia','AS','https://en.wikipedia.org/wiki/Saudi_Arabia','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ù…Ù…Ù„ÙƒØ© Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© Ø§Ù„Ø³Ø¹ÙˆØ¯ÙŠØ©,Ø§Ù„Ù…Ø·Ø§Ø±Ø§Øª Ù„Ù…ÙˆØ³Ù… Ø§Ù„Ø­Ø¬');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302781,'SB','Solomon Islands','OC','https://en.wikipedia.org/wiki/Solomon_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302596,'SC','Seychelles','AF','https://en.wikipedia.org/wiki/Seychelles',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302597,'SD','Sudan','AF','https://en.wikipedia.org/wiki/Sudan','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„Ø³ÙˆØ¯Ø§Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302715,'SE','Sweden','EU','https://en.wikipedia.org/wiki/Sweden','Flygplatserna i Sverige');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302661,'SG','Singapore','AS','https://en.wikipedia.org/wiki/Singapore',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302598,'SH','Saint Helena','AF','https://en.wikipedia.org/wiki/Saint_Helena',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302716,'SI','Slovenia','EU','https://en.wikipedia.org/wiki/Slovenia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302717,'SK','Slovakia','EU','https://en.wikipedia.org/wiki/Slovakia','letisko Slovenska');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302599,'SL','Sierra Leone','AF','https://en.wikipedia.org/wiki/Sierra_Leone',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302718,'SM','San Marino','EU','https://en.wikipedia.org/wiki/San_Marino',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302600,'SN','Senegal','AF','https://en.wikipedia.org/wiki/Senegal','AÃ©roports du SÃ©nÃ©gal');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302601,'SO','Somalia','AF','https://en.wikipedia.org/wiki/Somalia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302800,'SR','Suriname','SA','https://en.wikipedia.org/wiki/Suriname',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302614,'SS','South Sudan','AF','https://en.wikipedia.org/wiki/South_Sudan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302602,'ST','SÃ£o TomÃ© and Principe','AF','https://en.wikipedia.org/wiki/SÃ£o_TomÃ©_and_Principe',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302752,'SV','El Salvador','NA','https://en.wikipedia.org/wiki/El_Salvador','Salvadorian, Salvadorean');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302761,'SX','Sint Maarten','NA','https://en.wikipedia.org/wiki/Sint_Maarten',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302662,'SY','Syria','AS','https://en.wikipedia.org/wiki/Syria','Ù…Ø·Ø§Ø±Ø§Øª Ø³ÙˆØ±ÙŠØ§');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302603,'SZ','Eswatini','AF','https://en.wikipedia.org/wiki/Eswatini','Swaziland');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302753,'TC','Turks and Caicos Islands','NA','https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302604,'TD','Chad','AF','https://en.wikipedia.org/wiki/Chad',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302617,'TF','French Southern Territories','AN','https://en.wikipedia.org/wiki/French_Southern_Territories',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302605,'TG','Togo','AF','https://en.wikipedia.org/wiki/Togo',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302663,'TH','Thailand','AS','https://en.wikipedia.org/wiki/Thailand','Siam, Siamese');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302664,'TJ','Tajikistan','AS','https://en.wikipedia.org/wiki/Tajikistan','Tajik');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302782,'TK','Tokelau','OC','https://en.wikipedia.org/wiki/Tokelau',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302665,'TL','Timor-Leste','AS','https://en.wikipedia.org/wiki/Timor-Leste','East Timor');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302666,'TM','Turkmenistan','AS','https://en.wikipedia.org/wiki/Turkmenistan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302606,'TN','Tunisia','AF','https://en.wikipedia.org/wiki/Tunisia','Ù…Ø·Ø§Ø±Ø§Øª ØªÙˆÙ†Ø³');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302783,'TO','Tonga','OC','https://en.wikipedia.org/wiki/Tonga',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302667,'TR','Turkey','AS','https://en.wikipedia.org/wiki/Turkey','TÃ¼rkiye havaalanlarÄ±');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302754,'TT','Trinidad and Tobago','NA','https://en.wikipedia.org/wiki/Trinidad_and_Tobago',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302784,'TV','Tuvalu','OC','https://en.wikipedia.org/wiki/Tuvalu',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302668,'TW','Taiwan','AS','https://en.wikipedia.org/wiki/Taiwan',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302607,'TZ','Tanzania','AF','https://en.wikipedia.org/wiki/Tanzania',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302719,'UA','Ukraine','EU','https://en.wikipedia.org/wiki/Ukraine','ÐÐµÑ€Ð¾Ð¿Ð¾Ñ€Ñ‚Ð¸ Ð£ÐºÑ€Ð°Ñ—Ð½Ð¸');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302608,'UG','Uganda','AF','https://en.wikipedia.org/wiki/Uganda',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302785,'UM','United States Minor Outlying Islands','OC','https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302755,'US','United States','NA','https://en.wikipedia.org/wiki/United_States','America');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302801,'UY','Uruguay','SA','https://en.wikipedia.org/wiki/Uruguay','Aeropuertos de Uruguay');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302669,'UZ','Uzbekistan','AS','https://en.wikipedia.org/wiki/Uzbekistan','Uzbek');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302721,'VA','Vatican City','EU','https://en.wikipedia.org/wiki/Vatican_City','The Holy See');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302756,'VC','Saint Vincent and the Grenadines','NA','https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302802,'VE','Venezuela','SA','https://en.wikipedia.org/wiki/Venezuela','Aeropuertos de Venezuela');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302757,'VG','British Virgin Islands','NA','https://en.wikipedia.org/wiki/British_Virgin_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302758,'VI','U.S. Virgin Islands','NA','https://en.wikipedia.org/wiki/U.S._Virgin_Islands',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302670,'VN','Vietnam','AS','https://en.wikipedia.org/wiki/Vietnam','CÃ¡c sÃ¢n bay cá»§a Viá»‡t Nam');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302786,'VU','Vanuatu','OC','https://en.wikipedia.org/wiki/Vanuatu',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302787,'WF','Wallis and Futuna','OC','https://en.wikipedia.org/wiki/Wallis_and_Futuna',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302788,'WS','Samoa','OC','https://en.wikipedia.org/wiki/Samoa',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302720,'XK','Kosovo','EU','https://en.wikipedia.org/wiki/Kosovo','Kosova');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302671,'YE','Yemen','AS','https://en.wikipedia.org/wiki/Yemen','Ù…Ø·Ø§Ø±Ø§Øª Ø§Ù„ÙŠÙ…Ù†');
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302609,'YT','Mayotte','AF','https://en.wikipedia.org/wiki/Mayotte',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302610,'ZA','South Africa','AF','https://en.wikipedia.org/wiki/South_Africa',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302611,'ZM','Zambia','AF','https://en.wikipedia.org/wiki/Zambia',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302612,'ZW','Zimbabwe','AF','https://en.wikipedia.org/wiki/Zimbabwe',NULL);
INSERT INTO airport_data.COUNTRY(OBJECT_ID,COUNTRY_CODE,NAME,CONTINENT,WIKIPEDIA_LINK,KEYWORDS) VALUES(302613,'ZZ','Unknown or unassigned country','AF','https://en.wikipedia.org/wiki/Unknown_or_unassigned_country',NULL);